
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning



namespace Inprout.Data.Entities
{





    // User


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]

    public class User: Contracts.IDeletableEntity
    {


        public int Id { get; set; } // Id (Primary key)

        public System.Guid Uid { get; set; } // Uid

        public string FirstName { get; set; } // FirstName (length: 50)

        public string LastName { get; set; } // LastName (length: 50)

        public System.DateTime CreatedOn { get; set; } // CreatedOn

        public System.DateTime UpdatedOn { get; set; } // UpdatedOn

        public System.DateTime? DeletedOn { get; set; } // DeletedOn




    }



}
// </auto-generated>
