// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Inprout.Data.Context
{
    using Inprout.Data.Configuration;
    using Inprout.Data.Entities;

    public class InproutDbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<InproutDbContext>
    {
        public InproutDbContext Create()
        {
            return new InproutDbContext();
        }
    }
}
// </auto-generated>
